spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bookstore
    username: root
    password: thiyaga

logging:
  level:
    org:
      hibernate:
        Hibernate: info
        engine:
          query:
            spi: 
              sql: info
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
